name: Build

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install -y cmake llvm-dev clang libclang-dev lld zlib1g-dev libgc-dev
      - name: Build
        run: mkdir build && cd build && cmake .. && make -j$(nproc)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: twit-linux
          path: build/twitc

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install LLVM
        run: choco install llvm -y
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: twit-windows
          path: build/Release/twitc.exe
