name: Build and Release

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y cmake llvm-14-dev clang-14 libclang-14-dev lld-14 zlib1g-dev libgc-dev
      - name: Build
        run: mkdir build && cd build && cmake .. && make -j$(nproc)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: twit-linux
          path: build/twitc
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/twitc
          asset_name: twit-linux
          asset_content_type: application/octet-stream

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        run: choco install llvm --version=14.0.6 --allow-downgrade -y
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: twit-windows
          path: build/Release/twitc.exe
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/Release/twitc.exe
          asset_name: twit-windows.exe
          asset_content_type: application/octet-stream
